export enum USE_CASE_ERRORS {
    NONE = 'NONE',
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    VALUE_ALREADY_EXISTS = 'VALUE_ALREADY_EXISTS',
    VALUE_TOO_LONG = 'VALUE_TOO_LONG',
    VALUE_INVALID = 'VALUE_INVALID',
    VALUE_RESERVED = 'VALUE_RESERVED',
}
