/**
 * This class will produce GMCPPacket an provides a method to convert
 * GMCP message generated by application, to a proper Buffer read to be sent to communication layer
 *
 * To avoid dependency hell, this class is purely functionnal
 * To calling use case must send the Buffer to the communication layer
 *
 * This class pattern is a gateway : It can communicate with GMCP without exposing directly
 * the gmcp packet converter to the application layer
 *
 */
import { JsonValue } from '../../domain/types/JsonStruct';
import { GMCPPacket } from '../../libs/gmcp/GMCPPacket';
import { IGMCPGateway } from '../../application/ports/services/IGMCPGateway';

export class GMCPGateway implements IGMCPGateway {
    /**
     * This methods takes opcode + body and turn them to a valid Buffer
     * ready to be sent to client via communication layer
     * @param opcode
     * @param body
     */
    buildGMCPData(opcode: string, body: JsonValue): Buffer<ArrayBuffer> {
        const p = new GMCPPacket({ opcode, body });
        return p.render();
    }
}
