export enum STYLES {
    STYLE_NORMAL,
    STYLE_ITALIC,
    STYLE_CURSIVE,
    STYLE_MANUSCRIPT,
    STYLE_GOTHIC,
    STYLE_DECO,
    STYLE_GOTHIC_BOLD,
    STYLE_SANS,
    STYLE_SANS_BOLD,
    STYLE_SANS_ITALIC,
    STYLE_SANS_ITALIC_BOLD,
    STYLE_FLAT,
}
